//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VGR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviews
    {
        public long ID { get; set; }
        public long GameID { get; set; }
        public long UserID { get; set; }
        public string Username { get; set; }
        public string Review { get; set; }
    
        public virtual games games { get; set; }
        public virtual users users { get; set; }
    }
}
